FROM node:16.20.2-alpine

EXPOSE 8090

WORKDIR /usr/src/app

# Copy all of the source code
COPY . .

RUN npm install && npm run build && npm install -g serve && adduser -D frontuser

#RUN adduser -D frontuser

USER frontuser

CMD ["serve", "-s", "-l", "8090", "build"]
