version: '3.8'

services:
  frontend:
    container_name: frontend
    build: ./example-frontend
    ports:
      - 8090:8090
  backend:
    container_name: backend
    build: ./example-backend
    ports:
      - 8080:8080
